version: "2"
services:
  adminer:
    image: adminer:latest
    container_name: cbs-website.adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 3308:8080
    links:
      - mysql
  mysql:
    image: mysql:5.7.18
    container_name: cbs-website.mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cbs_website
      MYSQL_USER: cbs_website
      MYSQL_PASSWORD: cbs_website
      MYSQL_ROOT_PASSWORD: eRV6Hspr
    logging:
      driver: none